import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import postcss from "postcss";
import tailwindcss from "tailwindcss";
import autoprefixer from "autoprefixer";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * Tailwind CSS를 styles.css 로 빌드하는 esbuild 플러그인.
 * esbuild 빌드마다 전체 CSS 파이프라인(PostCSS + Tailwind + Autoprefixer)을 한 번 돌리고
 * 루트에 styles.css 파일로 저장한다.
 */
function tailwindPlugin() {
	return {
		name: "tailwind-css",
		setup(build) {
			const cssEntry = resolve(__dirname, "src/styles/globals.css");
			const cssOut = resolve(__dirname, "styles.css");

			const runPostcss = async () => {
				const css = readFileSync(cssEntry, "utf8");
				const result = await postcss([
					tailwindcss({ config: resolve(__dirname, "tailwind.config.ts") }),
					autoprefixer,
				]).process(css, { from: cssEntry, to: cssOut });
				writeFileSync(cssOut, result.css);
			};

			build.onStart(async () => {
				try {
					await runPostcss();
				} catch (err) {
					console.error("Tailwind build failed:", err);
				}
			});
		},
	};
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	jsx: "automatic",
	loader: {
		".ts": "ts",
		".tsx": "tsx",
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [tailwindPlugin()],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
