import type { TaskDetailData } from "../domain/taskDetailData";

export const mockTaskDetails: Record<string, TaskDetailData> = {
	"TASK-008": {
		id: "TASK-008",
		title: "UI/UX 레이아웃 설계",
		description:
			"Pharos 플러그인의 핵심 뷰 7개(Dashboard, Roadmap, 공개 진행도, 내 업무, 캘린더, 회의 목록, 회의 페이지)를 shadcn/ui 기반으로 설계하고 구현한다. 블록 구조로 props 기반 데이터 주입 패턴 확립.",
		startDate: "2026-04-22",
		endDate: "2026-04-25",
		status: "in-progress",
		priority: "HIGH",
		phase: "PLANNING",
		assignee: { id: "m1", name: "유석", role: "PO" },
		dependsOn: [{ id: "TASK-007", title: "Pharos 플러그인 초기 스캐폴딩" }],
		checklist: [
			{
				id: "c1",
				text: "Dashboard 레이아웃 목업",
				checked: true,
				checkedAt: "2026-04-23T18:30:00+09:00",
				checkedBy: "유석",
			},
			{
				id: "c2",
				text: "Roadmap 흐름 + 간트 차트 뷰",
				checked: true,
				checkedAt: "2026-04-24T10:55:00+09:00",
				checkedBy: "유석",
			},
			{
				id: "c3",
				text: "공개 진행도 페이지",
				checked: true,
				checkedAt: "2026-04-24T14:10:00+09:00",
				checkedBy: "유석",
			},
			{
				id: "c4",
				text: "내 업무 뷰 (개인 타임라인)",
				checked: true,
				checkedAt: "2026-04-24T16:30:00+09:00",
				checkedBy: "유석",
			},
			{
				id: "c5",
				text: "캘린더 뷰",
				checked: true,
				checkedAt: "2026-04-24T18:00:00+09:00",
				checkedBy: "유석",
			},
			{
				id: "c6",
				text: "회의 페이지 + Topic Page",
				checked: false,
				checkedAt: null,
				checkedBy: null,
			},
			{
				id: "c7",
				text: "Modal 9개 (프로젝트 생성 / 가입 / 회의 주제 등)",
				checked: false,
				checkedAt: null,
				checkedBy: null,
			},
		],
		linkedCommits: [
			{
				sha: "1839c75",
				message: "feat(TASK-008): Dashboard 리팩토링 - props 기반 구조",
				author: "유석",
				date: "2026-04-24T14:10:00+09:00",
				verifyResult: "verified",
				filesChanged: 5,
				linesAdded: 124,
				linesRemoved: 78,
			},
			{
				sha: "a8f3b21",
				message: "feat(TASK-008): 프로그레스 카드 프로토타입·개발 분리",
				author: "유석",
				date: "2026-04-24T13:45:00+09:00",
				verifyResult: "verified",
				filesChanged: 2,
				linesAdded: 54,
				linesRemoved: 12,
			},
			{
				sha: "c4e9d07",
				message: "feat(TASK-008): Roadmap 흐름/간트 토글",
				author: "유석",
				date: "2026-04-24T10:55:00+09:00",
				verifyResult: "verified",
				filesChanged: 3,
				linesAdded: 342,
				linesRemoved: 45,
			},
		],
		sourceMeetings: [
			{
				meetingId: "mtg-0422-adhoc",
				title: "UI/UX 초안 리뷰",
				date: "2026-04-22",
			},
			{
				meetingId: "mtg-0424-adhoc",
				title: "UI/UX 레이아웃 중간 리뷰",
				date: "2026-04-24",
			},
		],
	},
	"TASK-012": {
		id: "TASK-012",
		title: "Hocuspocus 서버 기본 구조",
		description:
			"Yjs + Hocuspocus 기반 문서 동기화 서버를 Oracle Cloud ARM에 올리고, JWT 인증 훅과 SQLite 영속 저장을 연결.",
		startDate: "2026-04-20",
		endDate: "2026-04-30",
		status: "in-progress",
		priority: "HIGH",
		phase: "DEVELOPMENT",
		assignee: { id: "m2", name: "경석", role: "PM" },
		dependsOn: [],
		checklist: [
			{
				id: "c1",
				text: "Oracle Cloud ARM 환경 세팅",
				checked: true,
				checkedAt: "2026-04-22T15:10:00+09:00",
				checkedBy: "경석",
			},
			{
				id: "c2",
				text: "Hocuspocus 서버 기본 구동",
				checked: true,
				checkedAt: "2026-04-22T17:30:00+09:00",
				checkedBy: "경석",
			},
			{
				id: "c3",
				text: "SQLite better-sqlite3 어댑터",
				checked: true,
				checkedAt: "2026-04-24T11:10:00+09:00",
				checkedBy: "경석",
			},
			{
				id: "c4",
				text: "JWT 토큰 검증 로직",
				checked: true,
				checkedAt: "2026-04-24T13:20:00+09:00",
				checkedBy: "경석",
			},
			{
				id: "c5",
				text: "onAuthenticate 훅 연결",
				checked: false,
				checkedAt: null,
				checkedBy: null,
			},
			{
				id: "c6",
				text: "CORS + HTTPS 배포",
				checked: false,
				checkedAt: null,
				checkedBy: null,
			},
		],
		linkedCommits: [
			{
				sha: "7b2c5f8",
				message: "feat(TASK-012): Hocuspocus onAuthenticate 훅 연결",
				author: "경석",
				date: "2026-04-24T13:50:00+09:00",
				verifyResult: "verified",
				filesChanged: 4,
				linesAdded: 89,
				linesRemoved: 3,
			},
			{
				sha: "5c9b1e2",
				message: "feat(TASK-012): Hocuspocus 서버 기본 구동",
				author: "경석",
				date: "2026-04-22T17:30:00+09:00",
				verifyResult: "verified",
				filesChanged: 6,
				linesAdded: 245,
				linesRemoved: 0,
			},
		],
		sourceMeetings: [
			{
				meetingId: "mtg-0420",
				title: "주간 정기 회의",
				date: "2026-04-20",
			},
		],
	},
};

export function getTaskDetailMock(taskId: string): TaskDetailData | null {
	return mockTaskDetails[taskId] ?? null;
}
